[package]
name = "fritzctrl"
version = "0.3.0"
authors = ["Robert Krahn <robert.krahn@gmail.com>"]
edition = "2018"
license = "MIT"
description = """
A utility for controlling AVM Fritz devices using the \"AVM Home Automation\" API
(https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf).
"""

[dependencies]
anyhow = "1.0"
chrono = "0.4.19"
clap = "2.33.3"
crossbeam-channel = "0.5.0"
env_logger = "0.8.2"
lazy_static = "1.4.0"
log = "0.4.13"
notify = "4.0.15"
regex = "1.4.2"
sunrise = "1.0.0"
timer = "0.2.0"
parse_duration = "2.1.0"
prettytable-rs = "0.8.0"
fritzapi = { path = "../fritzapi", version = "0.3.0" }

[target.'cfg(target_os = "macos")'.dependencies]
corelocation-rs = { git = "https://github.com/nthapaliya/corelocation-rs" }
