[package]
name = "fritzapi"
version = "0.3.0"
authors = ["Robert Krahn <robert.krahn@gmail.com>"]
edition = "2018"
license = "MIT"
description = """
Library for interfacing with the \"AVM Home Automation\" API
(https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf).
"""
keywords = ["avm", "fritz", "homeautomation", "dect", "smarthome", "outlet"]

[dependencies]
lazy_static = "1.4.0"
log = "0.4.13"
md5 = "0.7.0"
regex = "1.4.2"
serde = {version = "1.0.120", features = ["derive"]}
serde-xml-rs = "0.4.0"
thiserror = "1.0.23"

[dependencies.reqwest]
version = "0.11.0"
features = ["blocking", "rustls-tls"]
default-features = false
